debug = true
checkNewVersion = false
logLevel = "DEBUG"

defaultEntryPoints = ["http"]

InsecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
    address = ":80"
[retry]

[docker]
endpoint = "tcp://swarm-master.hutter.cloud:2376"
watch = true
swarmmode = true
exposedbydefault = false

[docker.tls]
ca = "/run/secrets/swarm-ca"
cert = "/run/secrets/swarm-cert"
key = "/run/secrets/swarm-key"
insecureskipverify = true

[web]
address = ":8080"
readOnly = true
